project_id = "idotyktgeqkpsypmztrg"

[functions.setup-stripe-products]
verify_jwt = false

[functions.generate-order-pdf]
verify_jwt = true

[functions.generate-dental-image]
verify_jwt = true

[functions.generate-price-table-pdf]
verify_jwt = true

[functions.check-appointment-reminders]
verify_jwt = true

[functions.generate-monthly-report-pdf]
verify_jwt = true

[functions.generate-receipt-pdf]
verify_jwt = true
